CXX=g++
CFLAGS=-g -Wall -I./include -I./src

all: test/regress_case test/regress_file test/regress_prefix

test/regress_prefix: src/trie.cc src/trie_impl.cc test/regress_prefix.cc
	$(CXX) $(CFLAGS) -o $@ $^

test/regress_file: src/trie.cc src/trie_impl.cc test/regress_file.cc
	$(CXX) $(CFLAGS) -o $@ $^

test/regress_case: src/trie.cc src/trie_impl.cc test/regress_case.cc
	$(CXX) $(CFLAGS) -o $@ $^

